import { StyleSheet } from 'react-native';
import { bluePhone, paleGreen } from '../../styles/colors';

export default StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  photo: {
    marginTop: 50,
    width: 200,
    height: 200,
    borderRadius: 200 / 2,
  },
  photoButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 20,
  },
  button: {
    padding: 10,
    backgroundColor: '#D3D3D3',
    color: 'black',
    marginHorizontal: 10,
    width: 130,
    textAlign: 'center',
    borderRadius: 8,
    overflow: 'hidden',
    height: 38,
  },
  addButton: {
    backgroundColor: bluePhone,
    padding: 10,
    color: 'white',
    marginHorizontal: 10,
    width: 130,
    textAlign: 'center',
    borderRadius: 8,
    overflow: 'hidden',
    height: 38,
  },
  disabledButton: {
    backgroundColor: "grey",
    padding: 10,
    color: 'white',
    marginHorizontal: 10,
    width: 130,
    textAlign: 'center',
    borderRadius: 8,
    overflow: 'hidden',
    height: 38,
  },
  label: {
    fontSize: 16,
    marginBottom: 2,
    color: '#818181',
    alignSelf: 'stretch',
    paddingLeft: 20,
  },
  fieldWrap: {
    alignSelf: 'stretch',
    marginHorizontal: 20,
    paddingBottom: 20,
  },
  field: {
    fontWeight: 'bold',
    paddingVertical: 5,
    paddingHorizontal: 10,
    fontSize: 22,
    borderColor: bluePhone,
    borderWidth: 1.5,
    borderRadius: 5,
  },
  phoneNrView: {
    marginLeft: 20,
    marginRight: 20,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 5,
    alignSelf: 'stretch',
    borderWidth: 1,
    borderRadius: 4,
    backgroundColor: '#DCDCDC',
  },
  phoneNr: {
    padding: 4,
    fontSize: 18,
    color: bluePhone,
  },
});
